# Generated by Django 4.0.4 on 2022-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date Of Visit')),
                ('price', models.IntegerField()),
                ('cards_accepted', models.CharField(choices=[('T', 'TRUE'), ('F', 'FALSE')], default='T', max_length=1)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
