# Generated by Django 4.0.4 on 2022-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='price',
            field=models.FloatField(),
        ),
    ]
