# Generated by Django 4.0.4 on 2022-05-03 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltank_app', '0003_station_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='price',
        ),
        migrations.AddField(
            model_name='station',
            name='midgrade',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='premium',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='regular',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
            preserve_default=False,
        ),
    ]
