# Generated by Django 4.0.4 on 2022-05-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulltank_app', '0005_station_city_station_state_station_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulltank_app.station')),
            ],
        ),
    ]
